# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build & Deploy

run-name: Build and deploy by @${{ github.actor }}

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Create env file
      run: |
         touch .env.production.local
         echo "${{ secrets.ENV_PROD }}" >> .env.production.local
        
    - name: Install dependencies
      run: npm install
      
    - name: Build production
      run: npm run build --if-present

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: application artifacts
        path: .next

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: application artifacts
        path: .next

    - name: Upload to hosting
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: ".next"
        target: "/opt/marketplace/frontend/marketplace-web"
        overwrite: true

    - name: Executing remote ssh commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          pm2 restart marketplace-web

  report:
    if: ${{ always() }}
    needs: [build, deploy]
    runs-on: ubuntu-latest

    steps:
    - name: Send GitHub Action trigger data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.26.0
      with:
        payload: |
          {
          	"blocks": [
          		{
          			"type": "section",
          			"text": {
          				"text": "*Marketplace Web* action report triggered by *_${{ github.actor }}_*.",
          				"type": "mrkdwn"
          			},
          			"fields": [
          				{
          					"type": "mrkdwn",
          					"text": "*Build*"
          				},
          				{
          					"type": "mrkdwn",
          					"text": "*Deploy*"
          				},
          				{
          					"type": "plain_text",
          					"text": "${{ needs.build.result }}"
          				},
          				{
          					"type": "plain_text",
          					"text": "${{ needs.deploy.result }}"
          				}
          			]
          		}
          	]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

