# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build & Deploy

run-name: Build and deploy by @${{ github.actor }}

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Create env file
      run: |
         touch .env.production.local
         echo "${{ secrets.ENV_PROD }}" >> .env.production.local
        
    - name: Install dependencies
      run: npm install
      
    - name: Build production
      run: npm run build --if-present

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: application artifacts
        path: .next

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: application artifacts
        path: .next

    - name: Upload to hosting
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: ".next"
        target: "/opt/marketplace/frontend"
        overwrite: true

